### ISSUE TITLE
Class SilverStripe\Discoverer\Service\SearchServiceAdaptor does not exist

### ISSUE THREAD

**Issue by vinstah** [silverstripeltd/silverstripe-discoverer#11]
## Module version

Which tagged version (or commit hash) are you using?
1.0.0
39bcae0360699f222e70ca6af99b9b362f292831

## Problem statement

After following the [simple search setup ](https://github.com/silverstripeltd/silverstripe-discoverer/blob/main/docs/simple-usage.md)I'm getting an error `Class SilverStripe\Discoverer\Service\SearchServiceAdaptor does not exist`

## Steps to reproduce
Set up controller to search from the basic setup guide
https://github.com/silverstripeltd/silverstripe-discoverer/blob/main/docs/simple-usage.md

## Additional context
I've removed my vendor folder and re-run composer install and composer cache-clear

**Comment by chrispenny** [comment]
@vinstah can I please confirm that you also installed an [integration module](https://github.com/silverstripeltd/silverstripe-discoverer/blob/main/README.md#available-service-integration-modules)?

This is the error you receive if no integration module is installed.

I will update some docs in the meantime to try and make it a bit more clear that this module won't work without an integration module.

**Comment by chrispenny** [comment]
I've updated the module docs, and at the moment I'm assuming this error was because there wasn't an integration module installed.

Please let me know if that's not the case though, and I can re-open.
